### ISSUE TITLE
Prevent building pages/links to dates later/earlier than 3 years from now

### ISSUE THREAD

**Issue by ashybaye** [ITS-UofIowa/uiowa_events#125]
Here is an issue that we at Tippie discovered. The Next/Prev links create event pages way into the future and back, for example - https://tippie.uiowa.edu/events/day/100000000-07-20
It would be great if there were the cut-off dates for, say, 3 years forward/back, and the links to future dates after that were not built (same for the past events earlier than 3 years).
The cut-off date can be discussed. We thought +/-3 years is a reasonable time window.

**Comment by richardbporter** [comment]
I started working on this: https://github.com/ITS-UofIowa/uiowa_events/compare/issue-125?expand=1

**Comment by adamdelaney** [comment]
I've tested the 404 for url navigation +3 and -3 years. After speaking with @richardbporter I don't think we are going to implement the date_nav logic because of all the relative date config required for date comparisons.

**Comment by richardbporter** [comment]
Its unlikely anyone will click enough to get that far backwards/forwards. The 404 is enough to stop bots from spamming these pagers.

**Comment by richardbporter** [comment]
Also, these pagers might not be in the long-term plan for this module.
