### ISSUE TITLE
Single event page produces a 404 when 'Single event path' contains more than one component.

### ISSUE THREAD

**Issue by ashybaye** [ITS-UofIowa/uiowa_events#130]
For example, 'events/event'.

**Comment by richardbporter** [comment]
I don't think the module can support this as there is no way to differentiate an event ID from a path component. We should prevent people from configuring the single event path as such in uiowa_events_config_form_validate().

**Comment by richardbporter** [comment]
Ugh. Looks like the single event path is not required. That makes the logic at https://github.com/ITS-UofIowa/uiowa_events/pull/129/files#diff-a41b3012c5f6901129e1d3c48fdfb38aR37 unreliable.

**Comment by richardbporter** [comment]
But everything breaks when left blank. I feel like it should be required...

**Comment by ashybaye** [comment]
Agree with the plan above!

**Comment by adamdelaney** [comment]
I don't think we need to write the update hook since it currently doesn't work with multiple path components as of now.
