### ISSUE TITLE
Descriptive page title

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/uiowa_events#32]
Provide a more descriptive page title. For example Events for Today or Events for September 2016.

**Comment by brandonneil** [comment]
The basic functionality for this used to exist: https://github.com/ITS-UofIowa/uiowa_events/commit/d88d62538f35dd593d29eb18779a5a71e89b20e8

**Comment by adamdelaney** [comment]
This looks like it relates to the primary tab titles. This issue was in regards to drupal_set_title().

**Comment by brandonneil** [comment]
oh gotcha, yea, makes sense.
