### ISSUE TITLE
Ability to filter more granularly 

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/uiowa_events#36]
This may pertain more to the pane widget, but it has been requested that you could filter by sub-departments, keywords, locations, etc.

**Comment by brandonneil** [comment]
I wonder if we should split this up (or at least define) the types of filters requested. So far, I've heard:

- More filter/granularity on events list configuration "Events Filter ID" (do multiple filters work and how?)
- Expose a search box on the main events list
- Pane widget filtering - perhaps how the localist_pane config works.

**Comment by genjohnson** [comment]
I'm closing this issue as separate issues have been created for the various types of filters identified here.
