### ISSUE TITLE
More filter/granularity on events list configuration "Events Filter ID" (do multiple filters work and how?)

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/uiowa_events#40]
From #36

**Comment by adamdelaney** [comment]
We need to look closer at the localist api to get this working. It appears like localist_pane is accounting for more robust filter options by combining or excluding filters. We could use this as a starting point for our own api calls in uiowa_events_load. The params are getting pretty cluttered in there so we may need to look at refactoring those as well.

**Comment by adamdelaney** [comment]
The localist knowledge base has example api calls: http://support.localist.com/article/localist-api/. I found this example for multiple types.

**Example:**
http://calendar.ecu.edu/api/2/events?type=27748&type=20195&match=all

**Comment by adamdelaney** [comment]
This issue is blocked until uiowa_events_load can accept multiple type params.

**Comment by adamdelaney** [comment]
Also look at this: 
Filter Parameters
Restrict the returned events based on filter items, tags and keywords assigned.

To specify multiple values for type, keyword or exclude_type, the parameter may be repeated with brackets ([]) after the name.

For instance, to request both keyword kw1 and kw2, use a URL similar to: http://CALENDAR-URL/api/2/events?keyword[]=kw1&keyword[]=kw2.

**Comment by adamdelaney** [comment]
A robust configuration form is now provided for the uiowa_events_pane. It would be nice to abstract this form to use for different renders.

**Comment by richardbporter** [comment]
Is this still an issue?
