### ISSUE TITLE
Print truncated description in teaser

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/uiowa_events#44]
This seems like a pretty common use case. It might be easier for people to unset rather than implement.

**Comment by joewhitsitt** [comment]
+1

i am running into this use case and having to preprocess the teaser to get what I want. so far I am tackling the issue two different ways. stripping all tags and then running truncate_utf8(), or relying on views, keeping some markup (links, etc) and using views_trim_text().
