### ISSUE TITLE
Add WAI-ARIA attributes to future instances toggle.

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/uiowa_events#70]
This is currently being flagged in FAE with the following:
- `span[class=future-instances-toggle singleevent-processed] - Add widget role to the SPAN element.`
- `span[class=future-instances-toggle singleevent-processed] - Add widget role(s) to the element and/or its descendants that accurately describe the user options and actions of the SPAN element with the following event handlers: onclick.`

Proposed Solution:
- add/toggle to expandable content:
  - `id`
  - `role="region"`
  - `aria-hidden`
  - `tabindex`
  - `aria-labeledby`
- add/toggle to the toggle:
  - `id`
  - `aria-expanded`
  - `aria-controls`
  - `aria-selected`
  - consider changing this from a span to a link.

**Comment by joewhitsitt** [comment]
Looks like a lot of this was taken care of by @richardbporter with #65 however, #71 addresses a bit more. Between the two, FAE no longer flags this functionality, but more can be done by adding the following:

add to `#future-instances`:
- `aria-labeledby`

add the dynamic `<a>`:
- `id`
- `aria-controls="future-instances"`
- `role="button"`
- `aria-selected` (toggle behavior)

Instead of wrangling jquery collapse, it might be easier to remove it and write our own js that handles all of this.

**Comment by richardbporter** [comment]
The `aria-labeledby`seems simple but what do you mean by 

> add the dynamic <a>:

**Comment by joewhitsitt** [comment]
the javascript library to toggle the show/hide of future instances dynamically creates an `<a>`, but it doesn't contain any a11y.
