### ISSUE TITLE
Update sites using uiowa_events

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/uiowa_events#75]
To work with the new event calendar system.

# 703

- [x] hpc.uiowa.edu  
- [x] theme.uiowa.edu                      
- [ ] informatics.uiowa.edu      
- [x] uc.uiowa.edu          
- [x] cee.engineering.uiowa.edu            
- [x] mie.engineering.uiowa.edu            
- [x] www.engineering.uiowa.edu            
- [x] tippie.uiowa.edu                     
- [x] cbe.engineering.uiowa.edu            
- [x] bme.engineering.uiowa.edu            
- [x] law.uiowa.edu                        
- [x] international.uiowa.edu              
- [x] ece.engineering.uiowa.edu
- [x] now.uiowa.edu

**Comment by richardbporter** [comment]
Sites overriding a uiowa_events theme function that will need to updated/removed:

- [ ] iisc.uiowa.edu
- [ ]   international.uiowa.edu
- [ ]   grantwood.uiowa.edu
- [ ]   artshare.uiowa.edu
- [ ]   law.uiowa.edu
- [ ]   informatics.uiowa.edu
- [ ]   hpc.uiowa.edu
- [ ]   tippie.uiowa.edu
- [ ]   engineering.uiowa.edu
- [ ]   its.uiowa.edu

**Comment by adamdelaney** [comment]
## Engineering go live notes
- Merge https://github.com/ITS-UofIowa/engineering.uiowa.edu/pull/4 and create a new release. Rebuild production env and run updates.
- Merge https://github.com/ITS-UofIowa/sitenow_custom_profile/pull/225 and create a new release. Update system.make.yml and deploy.

**Comment by adamdelaney** [comment]
Closing since we've implemented the new event system.
