### ISSUE TITLE
Update sites using feeds to import events

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/uiowa_events#76]
# 702

- [x] intranet.oneit.uiowa.edu                        >> http://events.uiowa.edu/api/2/events?days=365&pp=100&type=33154 **bdickey**

# 703

- [ ] discover.research.uiowa.edu           >> http://events.uiowa.edu/api/2/events?type=32507&days=186 **genjohnson**
- [ ] discover.research.uiowa.edu           >> http://data.its.uiowa.edu/mastercal/custom?calendar=72&startdate=12-06-2014&enddate=12-08-2016 @genjohnson
- [x] diversity.uiowa.edu                   >> https://diversity.uiowa.edu/diversity-feed/localist-events @richardbporter  @briand44 
- [x] outreach.uiowa.edu                    >> http://events.uiowa.edu/api/2/events?type=43014&days=365&pp=100 @markahrens 
- [x] oldcap.uiowa.edu                      >> http://events.uiowa.edu/api/2/events?days=365&pp=100&type=40603&exclude_type=32941&match=all @richardbporter 
- [x] oldcap.uiowa.edu                      >> http://events.uiowa.edu/api/2/events?days=365&type[]=32941&type[]=40603&match=all&distinct=true @richardbporter 
- [x] arts.uiowa.edu                        >> https://arts.uiowa.edu/arts-feed/localist-events @richardbporter
- [x] teach.its.uiowa.edu                   >> https://events.uiowa.edu/api/2/events?distinct=true&days=365&pp=100&type=33159 @joewhitsitt [PR32](https://github.com/ITS-UofIowa/teach.its.uiowa.edu/pull/32)
- [x] careers.uiowa.edu                     >> https://data.its.uiowa.edu/localist/careers @joewhitsitt [PR15](https://github.com/ITS-UofIowa/careers.uiowa.edu/pull/15)
- [x] careers.uiowa.edu                     >> http://data.its.uiowa.edu/mastercal/custom-udq?calendar=73&startdate=01-01-2000&enddate=01-01-2050 @joewhitsitt cleanup
- [x] pharmacy.uiowa.edu                    >> http://events.uiowa.edu/api/2/events?days=365&pp=100&type=36292 @briand44 
- [x] mnh.uiowa.edu                         >> http://events.uiowa.edu/api/2/events?days=365&pp=100&type=40604&exclude_type=32941&match=all @richardbporter 
- [x] mnh.uiowa.edu                         >> http://events.uiowa.edu/api/2/events?days=365&type[]=32941&type[]=40604&match=all&distinct=true @richardbporter 
- [x] international.uiowa.edu               >> https://data.its.uiowa.edu/localist/ip.php @joewhitsitt  cleanup

**Comment by genjohnson** [comment]
discover.research.uiowa.edu is using Localist widgets instead of custom views, so the feeds can be deleted. The steps to replace the panes have been documented in #78
