### ISSUE TITLE
Update sites using uiowa_events_paragraph

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/uiowa_events#77]
Is there a separate repo for that code?

~~inspire.uiowa.edu                     >>                    Status           :  enabled~~ - i think this is inncorrect

- [ ] - international.uiowa.edu (DEV)
- [ ] - tippie.uiowa.edu
- [ ] - law.uiowa.edu

**Comment by richardbporter** [comment]
@joewhitsitt You can add your dev/stage IP site to this.

**Comment by joewhitsitt** [comment]
- international.uiowa.edu (DEV)
- tippie.uiowa.edu

**Comment by joewhitsitt** [comment]
it does not have a repo. sounds like it will be living in here soon. ;)

**Comment by joewhitsitt** [comment]
These sites will have to use the following version on the day of the switch and run updates: https://github.com/ITS-UofIowa/uiowa_events_paragraph/tree/7.x-2.x

**Comment by adamdelaney** [comment]
Closing since we've implemented the new event system.
