### ISSUE TITLE
Update sites with Localist widget

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/uiowa_events#78]
Sites with a widget in a custom block:
- [x] oneit.uiowa.edu @adamdelaney
- [x] hpc.uiowa.edu @genjohnson will replace with uiowa_events
- [x] careers.uiowa.edu @joewhitsitt  will remove

Sites with a widget in a custom pane:
- [x] tier.uiowa.edu @briand44 will remove/replace with uiowa_events
- [x] informatics.uiowa.edu @genjohnson @dhannad will replace with uiowa_events
- [x] archaeology.uiowa.edu @genjohnson @dhannad will replace with uiowa_events
- [x] research.uiowa.edu (@see [ovpred_researcherprofdev.inc#L83](https://github.com/ITS-UofIowa/research.uiowa.edu/blob/3076ace8b0951b50235f7b8dc257d38c879fa7f7/modules/custom/ovpred_panes/plugins/content_types/ovpred_researcherprofdev.inc#L83)) @genjohnson will deal with this
- [x] its.uiowa.edu (@see [its_taxonomies.module#L183-L185](https://github.com/ITS-UofIowa/its.uiowa.edu/blob/3966ba897759d751d5ef3c3844da8d2834d5640d/modules/custom/its_taxonomies/its_taxonomies.module#L183-L185)) - [Will be resolved with PR 100](https://github.com/ITS-UofIowa/its.uiowa.edu/pull/100)

**Comment by genjohnson** [comment]
@joewhitsitt A client brought to my attention that our database searches failed to identify sites using the Localist widget in code (e.g., if a pane was provided by a custom feature only in code).

I [searched our GitHub organization for "events.uiowa.edu/widget"](https://github.com/search?q=org%3AITS-UofIowa+%22events.uiowa.edu%2Fwidget%22&type=Code) and added the sites it found to this task, including ITS.

IIRC, ITS was already on your radar and Tracy Scott has already approved removing the events, but I just wanted to mention it here in case I'm remembering incorrectly.

**Comment by joewhitsitt** [comment]
Yes, thank you for looking. I have updated the check list.

**Comment by genjohnson** [comment]
What needs to be done to update the sites that are left...

## informatics.uiowa.edu

1. replace custom pane on front page with pane from uiowa_events
2. regenerate the feature `informatics_pages`
3. update theme to style uiowa_events pane 

## archaeology.uiowa.edu

1. delete `archaeology_events` & `archaeology_event_views` features (they have already been uninstalled on dev, test & prod) 
2. replace "Upcoming Events" custom pane on front page with pane from uiowa_events
3. replace "Upcoming Events" custom pane on `/upcoming-events` with pane from uiowa_events**
4. regenerate the feature `archaeology_panels`
5. update theme to style uiowa_events panes

** until https://github.com/ITS-UofIowa/uiowa_events/issues/112 is addressed, at which time this custom page can be deleted


## research.uiowa.edu
Updating this site is complicated because the custom pane (which is defined in code) includes more content than just the Localist widget. I'll tackle this one, either by pre-processing a pane provided by uiowa_events to add the additional content or replacing the existing pane with 2 panes (1 with the custom content and 1 from uiowa_events).
