### ISSUE TITLE
Single event does not handle multiple dates accurately

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/uiowa_events#98]
My guess is that we need to look at the sing_event preprocessor as well as the js behavior.
See demo node: https://content.stage.drupal.uiowa.edu/test-event-multiple-instances.
### Here is the render:
<img width="844" alt="screen shot 2018-06-05 at 10 24 37 am" src="https://user-images.githubusercontent.com/1016880/40986158-251c3356-68ab-11e8-8fd8-e3c0186e5b4a.png">

**Comment by joewhitsitt** [comment]
This is not broken. The single template preprocess is only getting the next 10: https://github.com/ITS-UofIowa/uiowa_events/blob/7.x-2.x/includes/uiowa_events.single_event.inc#L49

**Comment by adamdelaney** [comment]
Shouldn't it return all date date instances?

**Comment by adamdelaney** [comment]
Also I would expect to return the next upcoming date_instance not the first.

**Comment by richardbporter** [comment]
I think it'd be safe to get all of them since we're expanding/collapsing the wrapper.
